# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS (NEON)
# ==========================================

spring.datasource.url=jdbc:postgresql://ep-ancient-darkness-aqdk53y2-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tqFO1cz2CMhl

# ==========================================
# CONFIGURACIÓN DE HIBERNATE Y JPA
# ==========================================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ver los valores que se envían a la base de datos (los ? del SQL)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970